import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Joaquin In Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>

        <main className={styles.main}>
          <nav className="navbar d-flex justify-content-between">
            <img alt="logo"/>
            
            <ul className="container">
              <li><a href="">Resume</a></li>
              <li><a href="">Get in Touch</a></li>
            </ul>

          </nav>
        </main>

        <footer className={styles.footer}>
          
        </footer>
      </body>
    </div>
  )
}
